version: "3"

tasks:
    protoc-go-gen:
        desc: "Generate .go files from .proto files"
        cmds:
            - rm -rf ./pkg/client/*
            - |
                protoc -I ./api ./api/order.proto --go_out=./pkg/client \
                --validate_out="lang=go,paths=source_relative:./pkg/client" \
                --go_opt=paths=source_relative --go-grpc_out=./pkg/client \
                --go-grpc_opt=paths=source_relative
    run-local:
        desc: "Run service on a local machine"
        cmds:
            - go run ./cmd/order_service/main.go
    test:
        desc: "Run all rests"
        cmds:
            - go clean -testcache
            - gotestsum --format-hide-empty-pkg --format-icons hivis -- -coverprofile=cover.out ./...
    goose-up-local:
        desc: "Up all migrations"
        cmds:
            - |
                env \
                GOOSE_DRIVER=postgres \
                GOOSE_DBSTRING="postgres://user:password@localhost:5432/order_service_db?sslmode=disable" \
                GOOSE_MIGRATION_DIR=migrations \
                goose up
    goose-down-local:
        desc: "Down all migrations"
        cmds:
            - |
                env \
                GOOSE_DRIVER=postgres \
                GOOSE_DBSTRING="postgres://user:password@localhost:5432/order_service_db?sslmode=disable" \
                GOOSE_MIGRATION_DIR=migrations \
                goose down
